spring:
  application:
    name: GeyserDump
  data:
    mongodb:
      host: 127.0.0.1
      authentication-database: admin
      database: dump
      username: dump
      password: dump

server:
  port: 8082

springdoc:
  api-docs:
    path: "/openapi"
  show-actuator: false
  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: "alpha"
    path: "/docs/"
    show-common-extensions: true